server:
  port: 8060
  
spring:
  application:
    name: paas

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost/paas?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
 
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 
    timeout: 500
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
      
paas:
  upload-path: E:\\test\\paas\\upload
  apps-root: E:\\test\\paas\\apps
  kube-config: E:\\test\\kube.config
  exclude-namespaces: kube-,ingress-
  
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["prometheus","health"]
      base-path: /
