spring:
  application:
    name: gateway
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
 
logging:
  file: logs/gateway.log
   
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["prometheus","health"]
      base-path: /